$.ajax({
  type:"GET",
  url:"http://bmclub.synology.me/board/notice.php?filter=1&keyword=&mod=list&page=0",
  dataType:"html",
  cache:false,
  success:function(data){
    debugger;
  },
  error:function(a,b,c){
    debugger;
  }
});
